### ISSUE TITLE
Backbone Router or React Router?

### ISSUE THREAD

**Issue by akfranco** [Volicon/NestedReact#1]
If starting from scratch and hoping just to use React for views, do you recommend using Backbone's router as well?

**Comment by gaperton** [comment]
Yes, why not. It's not the most important part of an application architecture, nor hard to replace in future, thus is's generally doesn't matter too much which one will you use.

And there's nothing wrong with backbone's router, all of routers are more or less the same with rather cosmetic differences. So, don't increase entropy, use the common and simplest one. If you will feel you need something different later, it can be replaced with almost no cost.

**Comment by gaperton** [comment]
Just looked at react-router a bit deeper. Last time when I looked at it, I missed some important details. In fact, taken in conjunction with React, it's the replacement not just for Backbone.Router, but for large and messy frameworks like Chaplin.

It's far superior to Backbone.Router, can not even be compared. Should be preferred with no doubts. https://github.com/rackt/react-router

**Comment by akfranco** [comment]
Thanks for the follow-up!
